/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#8a4e45",
        "inverse-primary": "#ffb4a8",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2dd",
        "primary-container": "#a46359",
        "secondary-container": "#dde3eb",
        "primary": "#874c42",
        "surface-variant": "#e4e2dd",
        "primary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#c1c7cf",
        "surface-container-high": "#eae8e3",
        "error": "#ba1a1a",
        "surface": "#fbf9f4",
        "tertiary-fixed-dim": "#d3c4b1",
        "primary-fixed-dim": "#ffb4a8",
        "error-container": "#ffdad6",
        "on-background": "#1b1c19",
        "on-error": "#ffffff",
        "on-surface-variant": "#524341",
        "surface-container-lowest": "#ffffff",
        "secondary": "#595f66",
        "surface-dim": "#dbdad5",
        "tertiary-fixed": "#f0e0cc",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c19",
        "outline": "#857370",
        "on-secondary": "#ffffff",
        "surface-container": "#f0eee9",
        "inverse-on-surface": "#f2f1ec",
        "on-primary-fixed": "#370d08",
        "on-secondary-container": "#5f656c",
        "on-tertiary-fixed": "#221a0e",
        "on-primary-fixed-variant": "#6e372f",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf9f4",
        "tertiary": "#655a4b",
        "background": "#fbf9f4",
        "on-tertiary-fixed-variant": "#4f4537",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed-variant": "#41474e",
        "inverse-surface": "#30312e",
        "secondary-fixed": "#dde3eb",
        "outline-variant": "#d7c2be",
        "surface-container-low": "#f5f3ee",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed": "#161c22",
        "tertiary-container": "#7e7362",
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body": ["var(--font-newsreader)", "Newsreader", "serif"],
        "label": ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
